import React, { createContext, useContext, useState } from 'react';

const LanguageContext = createContext();

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('en');
  const [currency, setCurrency] = useState('USD');

  const translations = {
    en: {
      dashboard: 'Dashboard',
      clients: 'Clients',
      projects: 'Projects',
      profile: 'Profile',
      userManagement: 'User Management',
      logout: 'Logout',
      create: 'Create',
      edit: 'Edit',
      delete: 'Delete',
      save: 'Save',
      cancel: 'Cancel',
      loading: 'Loading...',
      error: 'Error',
      success: 'Success',
      name: 'Name',
      email: 'Email',
      phone: 'Phone',
      address: 'Address',
      status: 'Status',
      date: 'Date',
      amount: 'Amount',
      total: 'Total',
      notes: 'Notes',
      paymentType: 'Payment Type',
      dueDate: 'Due Date',
      description: 'Description',
      quantity: 'Quantity',
      unitPrice: 'Unit Price',
      actions: 'Actions',
      search: 'Search',
      filter: 'Filter',
      all: 'All',
      draft: 'Draft',
      sent: 'Sent',
      accepted: 'Accepted',
      rejected: 'Rejected',
      paid: 'Paid',
      overdue: 'Overdue',
      pending: 'Pending',
      inProgress: 'In Progress',
      completed: 'Completed',
      cancelled: 'Cancelled',
      quote_sent: 'Quote Sent',
      quote_accepted: 'Quote Accepted',
      finished: 'Finished',
      check: 'Check',
      bankTransfer: 'Bank Transfer',
      crypto: 'Cryptocurrency',
      cash: 'Cash',
      other: 'Other',
      notSpecified: 'Not specified',
      back: 'Back',
      createQuote: 'Create Quote',
      createInvoice: 'Create Invoice',
      createProject: 'Create Project',
      createClient: 'Create Client',
      update: 'Update',
      confirm: 'Confirm',
      areYouSure: 'Are you sure?',
      thisActionCannotBeUndone: 'This action cannot be undone.',
      noDataFound: 'No data found',
      noQuotesYet: 'No quotes yet. Create your first quote!',
      noInvoicesYet: 'No invoices yet.',
      noProjectsYet: 'No projects yet.',
      noClientsYet: 'No clients yet.',
      memberSince: 'Member Since',
      maxAnnualTurnover: 'Max Annual Turnover',
      chargeRate: 'Charge Rate',
      fullName: 'Full Name',
      birthDate: 'Birth Date',
      phoneNumber: 'Phone Number',
      editProfile: 'Edit Profile',
      saveChanges: 'Save Changes',
      basicInformation: 'Basic Information',
      contactInformation: 'Contact Information',
      businessInformation: 'Business Information',
      accountInformation: 'Account Information',
      username: 'Username',
      role: 'Role',
      admin: 'Admin',
      user: 'User',
      darkMode: 'Dark Mode',
      lightMode: 'Light Mode',
      language: 'Language',
      currency: 'Currency',
      settings: 'Settings',
      annualActivitySummary: 'Annual Activity Summary',
      annualTurnover: 'Annual Turnover',
      pendingPayments: 'Pending Payments',
      unsentInvoices: 'Unsent Invoices',
      remainingToAchieve: 'Remaining to Achieve',
      progress: 'Progress',
      quarterlySummary: 'Quarterly Summary',
      paidTurnover: 'Paid Turnover',
      pendingTurnover: 'Pending Turnover',
      overdueTurnover: 'Overdue Turnover',
      totalTurnover: 'Total Turnover',
      monthlyTurnover: 'Monthly Turnover',
      annualEvolution: 'Annual Evolution',
      projectName: 'Project Name',
      clientName: 'Client Name',
      startDate: 'Start Date',
      endDate: 'End Date',
      projectDescription: 'Project Description',
      selectClient: 'Select Client',
      startDateRequired: 'Start date is required',
      endDateRequired: 'End date is required',
      endDateAfterStart: 'End date must be after start date',
      clientRequired: 'Client is required',
      nameRequired: 'Name is required',
      descriptionRequired: 'Description is required',
      createdOn: 'Created on',
      clientInformation: 'Client Information',
      projectInformation: 'Project Information',
      quotes: 'Quotes',
      invoices: 'Invoices',
      number: 'Number',
      selectPaymentType: 'Select payment type',
      totalAmount: 'Total Amount',
      lineItems: 'Line Items',
      addLineItem: 'Add Line Item',
      additionalNotes: 'Additional notes...',
      updateQuote: 'Update Quote',
      clientType: 'Client Type',
      person: 'Person',
      company: 'Company',
      firstName: 'First Name',
      lastName: 'Last Name',
      companyName: 'Company Name',
      firstNameRequired: 'First Name is required',
      lastNameRequired: 'Last Name is required',
      companyNameRequired: 'Company Name is required',
      emailRequired: 'Email is required',
      phoneRequired: 'Phone is required',
      addressRequired: 'Address is required',
      invalidEmail: 'Invalid email format',
      invalidPhone: 'Invalid phone format',
      personalInformation: 'Personal Information',
      professionalInformation: 'Professional Information',
      maximumAnnualTurnover: 'Maximum Annual Turnover (€)',
      pleaseEnterNumber: 'Please enter a number',
      prospect: 'Prospect',
      userManagement: 'User Management',
      admin: 'Admin',
      project: 'Project',
      noProject: 'No project',
      editQuote: 'Edit Quote',
      password: 'Password',
      overdueInvoices: 'Overdue invoices',
      overdueInvoicesDescription: 'Some sent invoices are past their due date.',
      clearFilters: 'Clear Filters',
      client: 'Client',
      sendEmail: 'Send Email',
      sendQuoteEmail: 'Send Quote Email',
      sendInvoiceEmail: 'Send Invoice Email',
      editInvoice: 'Edit Invoice',
      updateInvoice: 'Update Invoice',
      birthDateCannotBeInFuture: 'The birth date cannot be in the future',
      birthDateTooOld: 'The birth date seems too old',
      maxAnnualTurnoverCannotBeNegative: 'The annual turnover cannot be negative',
      chargeRateMustBeBetween0And100: 'The charge rate must be between 0 and 100%',
      emailSentSuccessfully: 'Email sent successfully',
      failedToLoadData: 'Failed to load data',
      userUpdatedSuccessfully: 'User updated successfully',
      userCreatedSuccessfully: 'User created successfully',
      errorSavingUser: 'Error saving user',
      areYouSureDeleteUser: 'Are you sure you want to delete this user?',
      userDeletedSuccessfully: 'User deleted successfully',
      errorDeletingUser: 'Error deleting user',
      passwordRequired: 'Password is required',
      passwordChangedSuccessfully: 'Password changed successfully',
      errorChangingPassword: 'Error changing password',
      accessDenied: 'Access denied (admin only)',
      changePassword: 'Change password',
      viewStats: 'View statistics',
      editUser: 'Edit user',
      newPassword: 'New password',
      change: 'Change',
      statsFor: 'Statistics for',
      stats: 'Statistics',
      country: 'Country',
      invoiceCreatedSuccessfully: 'Invoice created successfully',
      quoteCreatedSuccessfully: 'Quote created successfully',
      quoteInformation: 'Quote information',
      invoiceDetails: 'Invoice details',
      estimatedTurnover: 'Estimated Turnover',
      chargesToPay: 'Charges to Pay',
      estimatedCharges: 'Estimated Charges',
      pendingQuotesAmount: 'Pending Quotes Amount',
    },
    fr: {
      dashboard: 'Tableau de bord',
      clients: 'Clients',
      projects: 'Projets',
      profile: 'Profil',
      userManagement: 'Gestion des utilisateurs',
      logout: 'Déconnexion',
      create: 'Créer',
      edit: 'Modifier',
      delete: 'Supprimer',
      save: 'Enregistrer',
      cancel: 'Annuler',
      loading: 'Chargement...',
      error: 'Erreur',
      success: 'Succès',
      name: 'Nom',
      email: 'Email',
      phone: 'Téléphone',
      address: 'Adresse',
      status: 'Statut',
      date: 'Date',
      amount: 'Montant',
      total: 'Total',
      notes: 'Notes',
      paymentType: 'Type de paiement',
      dueDate: 'Date d\'échéance',
      description: 'Description',
      quantity: 'Quantité',
      unitPrice: 'Prix unitaire',
      actions: 'Actions',
      search: 'Rechercher',
      filter: 'Filtrer',
      all: 'Tous',
      draft: 'Brouillon',
      sent: 'Envoyé',
      accepted: 'Accepté',
      rejected: 'Refusé',
      paid: 'Payé',
      overdue: 'En retard',
      pending: 'Démarré',
      inProgress: 'En cours',
      completed: 'Terminé',
      clientType: 'Type de client',
      person: 'Personne',
      company: 'Entreprise',
      firstName: 'Prénom',
      lastName: 'Nom',
      companyName: 'Nom de l\'entreprise',
      firstNameRequired: 'Le prénom est requis',
      lastNameRequired: 'Le nom est requis',
      companyNameRequired: 'Le nom de l\'entreprise est requis',
      emailRequired: 'L\'email est requis',
      phoneRequired: 'Le téléphone est requis',
      addressRequired: 'L\'adresse est requise',
      invalidEmail: 'Adresse email invalide',
      invalidPhone: 'Le téléphone doit contenir 10 chiffres et commencer par 0',
      cancelled: 'Annulé',
      quote_sent: 'Devis envoyé',
      quote_accepted: 'Devis accepté',
      finished: 'Terminé',
      check: 'Chèque',
      bankTransfer: 'Virement bancaire',
      crypto: 'Cryptomonnaie',
      cash: 'Espèces',
      other: 'Autre',
      notSpecified: 'Non spécifié',
      back: 'Retour',
      createQuote: 'Créer un devis',
      createInvoice: 'Créer une facture',
      createProject: 'Créer un projet',
      createClient: 'Créer un client',
      update: 'Mettre à jour',
      confirm: 'Confirmer',
      areYouSure: 'Êtes-vous sûr ?',
      thisActionCannotBeUndone: 'Cette action ne peut pas être annulée.',
      noDataFound: 'Aucune donnée trouvée',
      noQuotesYet: 'Aucun devis pour le moment. Créez votre premier devis !',
      noInvoicesYet: 'Aucune facture pour le moment.',
      noProjectsYet: 'Aucun projet pour le moment.',
      noClientsYet: 'Aucun client pour le moment.',
      memberSince: 'Membre depuis',
      maxAnnualTurnover: 'Chiffre d\'affaires annuel max',
      chargeRate: 'Taux de charges',
      fullName: 'Nom complet',
      birthDate: 'Date de naissance',
      phoneNumber: 'Numéro de téléphone',
      editProfile: 'Modifier le profil',
      saveChanges: 'Enregistrer les modifications',
      basicInformation: 'Informations de base',
      contactInformation: 'Informations de contact',
      businessInformation: 'Informations professionnelles',
      accountInformation: 'Informations du compte',
      username: 'Nom d\'utilisateur',
      role: 'Rôle',
      admin: 'Administrateur',
      user: 'Utilisateur',
      darkMode: 'Mode sombre',
      lightMode: 'Mode clair',
      language: 'Langue',
      currency: 'Devise',
      settings: 'Paramètres',
      annualActivitySummary: 'Résumé annuel d\'activité',
      annualTurnover: 'Chiffre d\'affaires annuel',
      pendingPayments: 'Paiements en attente',
      unsentInvoices: 'Factures non envoyées',
      remainingToAchieve: 'Reste à atteindre',
      progress: 'Progression',
      quarterlySummary: 'Résumé trimestriel',
      paidTurnover: 'Chiffre d\'affaires payé',
      pendingTurnover: 'Chiffre d\'affaires en attente',
      overdueTurnover: 'Chiffre d\'affaires en retard',
      totalTurnover: 'Chiffre d\'affaires total',
      monthlyTurnover: 'Chiffre d\'affaires mensuel',
      annualEvolution: 'Évolution annuelle',
      projectName: 'Nom du projet',
      clientName: 'Nom du client',
      startDate: 'Date de début',
      endDate: 'Date de fin',
      projectDescription: 'Description du projet',
      selectClient: 'Sélectionner un client',
      startDateRequired: 'La date de début est requise',
      endDateRequired: 'La date de fin est requise',
      endDateAfterStart: 'La date de fin doit être après la date de début',
      clientRequired: 'Le client est requis',
      nameRequired: 'Le nom est requis',
      descriptionRequired: 'La description est requise',
      createdOn: 'Créé le',
      clientInformation: 'Informations du client',
      projectInformation: 'Informations du projet',
      quotes: 'Devis',
      invoices: 'Factures',
      number: 'Numéro',
      selectPaymentType: 'Sélectionner le type de paiement',
      totalAmount: 'Montant total',
      lineItems: 'Articles',
      addLineItem: 'Ajouter un article',
      additionalNotes: 'Notes supplémentaires...',
      updateQuote: 'Mettre à jour le devis',
      personalInformation: 'Informations personnelles',
      professionalInformation: 'Informations professionnelles',
      maximumAnnualTurnover: 'Chiffre d\'affaires annuel maximum (€)',
      pleaseEnterNumber: 'Veuillez saisir un nombre',
      prospect: 'Prospect',
      userManagement: 'Gestion des utilisateurs',
      admin: 'Administrateur',
      project: 'Projet',
      noProject: 'Aucun projet',
      editQuote: 'Modifier le devis',
      password: 'Mot de passe',
      overdueInvoices: 'Factures en retard',
      overdueInvoicesDescription: 'Certaines factures envoyées ont dépassé leur date limite de paiement.',
      clearFilters: 'Effacer les filtres',
      client: 'Client',
      sendEmail: 'Envoyer un email',
      sendQuoteEmail: 'Envoyer un email de devis',
      sendInvoiceEmail: 'Envoyer un email de facture',
      editInvoice: 'Modifier la facture',
      updateInvoice: 'Mettre à jour la facture',
      birthDateCannotBeInFuture: 'La date de naissance ne peut pas être dans le futur',
      birthDateTooOld: 'La date de naissance semble trop ancienne',
      maxAnnualTurnoverCannotBeNegative: 'Le chiffre d\'affaires ne peut pas être négatif',
      chargeRateMustBeBetween0And100: 'Le taux de charges doit être entre 0 et 100%',
      emailSentSuccessfully: 'Email envoyé avec succès',
      failedToLoadData: 'Échec du chargement des données',
      userUpdatedSuccessfully: 'Utilisateur mis à jour avec succès',
      userCreatedSuccessfully: 'Utilisateur créé avec succès',
      errorSavingUser: 'Erreur lors de la sauvegarde de l\'utilisateur',
      areYouSureDeleteUser: 'Êtes-vous sûr de vouloir supprimer cet utilisateur ?',
      userDeletedSuccessfully: 'Utilisateur supprimé avec succès',
      errorDeletingUser: 'Erreur lors de la suppression de l\'utilisateur',
      passwordRequired: 'Le mot de passe est requis',
      passwordChangedSuccessfully: 'Mot de passe modifié avec succès',
      errorChangingPassword: 'Erreur lors du changement de mot de passe',
      accessDenied: 'Accès refusé (administrateur uniquement)',
      changePassword: 'Changer le mot de passe',
      viewStats: 'Voir les statistiques',
      editUser: 'Modifier l\'utilisateur',
      newPassword: 'Nouveau mot de passe',
      change: 'Changer',
      statsFor: 'Statistiques pour',
      stats: 'Statistiques',
      country: 'Pays',
      invoiceCreatedSuccessfully: 'Facture créée avec succès',
      quoteCreatedSuccessfully: 'Devis créé avec succès',
      quoteInformation: 'Informations du devis',
      invoiceDetails: 'Détails de la facture',
      estimatedTurnover: 'Chiffre d\'affaires estimé',
      chargesToPay: 'Charges à payer',
      estimatedCharges: 'Charges estimées',
      pendingQuotesAmount: 'Montant des devis en attente',
    }
  };

  const currencies = {
    EUR: {
      symbol: '€',
      name: 'Euro',
      code: 'EUR'
    },
    USD: {
      symbol: '$',
      name: 'US Dollar',
      code: 'USD'
    }
  };

  const t = (key) => {
    return translations[language][key] || key;
  };

  const getCurrencySymbol = () => {
    return currencies[currency].symbol;
  };

  const getCurrencyName = () => {
    return currencies[currency].name;
  };

  const formatCurrency = (amount) => {
    const locale = language === 'fr' ? 'fr-FR' : 'en-US';
    const currencyCode = currency;
    
    // Gérer les valeurs null, undefined, NaN
    if (amount === null || amount === undefined || isNaN(amount)) {
      amount = 0;
    }
    
    return new Intl.NumberFormat(locale, {
      style: 'currency',
      currency: currencyCode,
      minimumFractionDigits: 2,
      maximumFractionDigits: 2
    }).format(amount);
  };

  const toggleLanguage = () => {
    setLanguage(language === 'en' ? 'fr' : 'en');
  };

  const toggleCurrency = () => {
    setCurrency(currency === 'EUR' ? 'USD' : 'EUR');
  };

  const value = {
    language,
    currency,
    t,
    getCurrencySymbol,
    getCurrencyName,
    formatCurrency,
    toggleLanguage,
    toggleCurrency,
    translations,
    currencies
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
}; 